### ISSUE TITLE
Splunk cloud issues

### ISSUE THREAD

**Issue by fraserc182** [geekusa/search_catalog#1]
Hi,

This app is exactly what I am looking for but I am having issues with using it in splunk cloud.
I have also noticed it says the version 1.2.0 is not available for the cloud, however I am able to install it using the app browser in splunk cloud.

Anyway, when I install the app, it does not create the lookup tables. I just downloaded the app and then copied the .csv files in and then the app was able to see the lookup files.
I then went to generate dashboards and hit submit, which seemed to work. Then upon pressing refresh I get an xml access denied error.
There is also no search catalog button and when I do try to use a search I simply get a 404 error.

Any help would be appreciated.

**Comment by geekusa** [comment]
Hi @fraserc182, full disclosure I am not a Splunk Cloud user so I can't speak 100% to that experience. I just updated recently the app so I'm not sure how long it takes Splunk to vet for Cloud. 

The app doesn't by default create lookup tables so that an upgrade will not destroy any existing data. The refresh button is taking advantage of the entity refresh (in this case for the views and nav) Splunk makes available on a Splunk host (/debug/refresh?entity=/data/ui/views&entity=/data/ui/nav) but perhaps doesn't allow this on Cloud. I will need to research if there is any other method of accomplishing this (maybe a REST call?).

**Comment by fraserc182** [comment]
Hi,

Thanks for getting back to me. I know it's a tall order to ask you for help on this so I appreciate any input you may have about it. The app is exactly what I am looking for now we're expanding splunk to other departments and users.

Thanks again for looking into it!

Cheers.

**Comment by geekusa** [comment]
@fraserc182  I have not been able to find much info related to Splunk Cloud and refreshing the nav and views. The documentation about refreshing can be seen here https://dev.splunk.com/enterprise/tutorials/quickstart/changenavigation/ but there is no mention of Splunk Cloud. It might be that the only method available to you is a restart which is not ideal. However there is documentation suggesting that support is able to open certain features of Cloud to specific ip ranges (such as what is seen in the API documentation https://docs.splunk.com/Documentation/SplunkCloud/latest/RESTTUT/RESTandCloud). Given this information I would suggest opening a support case with Splunk and showing them the first link I posted and ask if they can allow this ability on your instance to your IP range or if they have an alternative (to restarting). If you do open the support ticket please post back the results.

**Comment by fraserc182** [comment]
Hi,

Thanks for the comment, apologies for the late response.
I've just opened this with splunk support and I will let you know what they come back. If they say it's not possible I will just close this issue off.
Thanks for all your help.

**Comment by fraserc182** [comment]
Hi @geekusa, I got a response from the support team who have said that this is not something they would be able to help with unfortunately. So looks like there is no solution currently!

Thanks again for all your help on this, very much appreciate it.

**Comment by geekusa** [comment]
Sorry to hear that @fraserc182, though I do want to note that a restart is still a viable -- albeit not ideal -- option. Thanks for trying the support path though.
